# Generated by Django 5.2.17 on 2026-10-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_candidates', models.PositiveIntegerField(default=0)),
                ('total_recruiters', models.PositiveIntegerField(default=0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
